'use strict';

const chalk = require('chalk');
const path = require('path');
const fs = require('fs-extra');
const yaml = require('js-yaml');
const pluralize = require('pluralize');

const { isEva4jProject } = require('../utils/validator');
const { toCamelCase, toPascalCase } = require('../utils/naming');

async function generateSystemCommand() {
  const projectDir = process.cwd();

  if (!(await isEva4jProject(projectDir))) {
    console.error(chalk.red('❌ Not in an eva4j project directory'));
    console.error(chalk.gray('Run this command inside a project created with eva4j'));
    process.exit(1);
  }

  // ── Read system/system.yaml ───────────────────────────────────────────────
  const systemDir      = path.join(projectDir, 'system');
  const systemYamlPath = path.join(systemDir, 'system.yaml');

  if (!(await fs.pathExists(systemYamlPath))) {
    console.error(chalk.red('❌ system/system.yaml not found'));
    console.error(chalk.gray('Create system/system.yaml first (run: eva build-system-yaml)'));
    process.exit(1);
  }

  let systemConfig;
  try {
    const content = await fs.readFile(systemYamlPath, 'utf-8');
    systemConfig = yaml.load(content);
  } catch (err) {
    console.error(chalk.red('❌ Failed to parse system/system.yaml:'), err.message);
    process.exit(1);
  }

  const { modules = [] } = systemConfig;

  if (!modules.length) {
    console.log(chalk.yellow('⚠️  No modules defined in system/system.yaml'));
    process.exit(0);
  }

  console.log(chalk.blue('\n🚀 eva generate system\n'));
  console.log(chalk.gray('  Source : system/system.yaml'));
  console.log(chalk.gray('  Output : system/{module}.yaml\n'));

  // ── Generate one domain.yaml skeleton per module inside system/ ───────────
  await fs.ensureDir(systemDir);

  for (const mod of modules) {
    const outputPath = path.join(systemDir, `${mod.name}.yaml`);
    const existed    = await fs.pathExists(outputPath);
    const content    = buildDomainYaml(mod, systemConfig);
    await fs.writeFile(outputPath, content, 'utf-8');

    if (existed) {
      console.log(chalk.yellow(`  ♻️  system/${mod.name}.yaml overwritten`));
    } else {
      console.log(chalk.green(`  ✨ system/${mod.name}.yaml created`));
    }
  }

  console.log(chalk.blue(`\n✅ Generated ${modules.length} domain.yaml skeleton(s)\n`));
  console.log(chalk.white('Next steps:'));
  console.log(chalk.gray('  1. Open each system/{module}.yaml and complete entity fields'));
  console.log(chalk.gray('  2. Copy each file to its module source directory:'));
  console.log(chalk.gray('       src/main/java/<package>/<module>/domain.yaml'));
  console.log(chalk.gray('  3. Run: eva g entities <module>  (for each module)'));
  console.log();
}

// ── Domain YAML builder ───────────────────────────────────────────────────────

function buildDomainYaml(mod, systemConfig) {
  const integrations = systemConfig.integrations || {};
  const asyncEvents  = integrations.async || [];
  const syncCalls    = integrations.sync  || [];

  const moduleName    = mod.name;
  const aggregateName = toPascalCase(pluralize.singular(moduleName));
  const entityName    = aggregateName.charAt(0).toLowerCase() + aggregateName.slice(1);
  const tableName     = moduleName.replace(/-/g, '_');

  // Events this module produces
  const producedEvents = asyncEvents.filter(e => e.producer === moduleName);

  // Events this module consumes (one entry per consumer match)
  const consumedEvents = asyncEvents.flatMap(e =>
    (e.consumers || [])
      .filter(c => c.module === moduleName)
      .map(c => ({ ...e, consumerUseCase: c.useCase }))
  );

  // Sync calls this module makes as caller
  const outboundCalls = syncCalls.filter(s => s.caller === moduleName);

  // REST endpoints this module exposes
  const exposes = mod.exposes || [];

  const today = new Date().toISOString().split('T')[0];
  const lines = [];

  // ── Header ────────────────────────────────────────────────────────────────
  lines.push(`# ${mod.name}.yaml — domain model skeleton`);
  lines.push(`# Generated by: eva generate system  (${today})`);
  lines.push(`# Source: system/system.yaml`);
  lines.push(`#`);
  lines.push(`# ─── HOW TO COMPLETE THIS FILE ──────────────────────────────────────`);
  lines.push(`#  1. Add entity fields under aggregates[].entities[].fields`);
  lines.push(`#  2. Add enums / value objects as needed`);
  if (producedEvents.length)
    lines.push(`#  3. Add event payload fields under aggregates[].events[].fields`);
  if (consumedEvents.length)
    lines.push(`#  4. Add payload fields under listeners[].fields (match producer's event)`);
  if (outboundCalls.length)
    lines.push(`#  5. Add response fields under ports[].fields`);
  lines.push(`# ────────────────────────────────────────────────────────────────────`);
  lines.push(``);

  // ── aggregates ────────────────────────────────────────────────────────────
  lines.push(`aggregates:`);
  lines.push(`  - name: ${aggregateName}`);
  lines.push(`    entities:`);
  lines.push(`      - name: ${entityName}`);
  lines.push(`        isRoot: true`);
  lines.push(`        tableName: ${tableName}`);
  lines.push(`        audit:`);
  lines.push(`          enabled: true`);
  lines.push(`        fields:`);
  lines.push(`          - name: id`);
  lines.push(`            type: String`);
  lines.push(`          # TODO: add fields`);

  if (producedEvents.length) {
    lines.push(``);
    lines.push(`    events:`);
    for (const ev of producedEvents) {
      lines.push(`      - name: ${ev.event}`);
      lines.push(`        fields:`);
      lines.push(`          # TODO: add event payload fields`);
      lines.push(`          # - name: fieldName`);
      lines.push(`          #   type: String`);
    }
  }

  lines.push(``);

  // ── endpoints ─────────────────────────────────────────────────────────────
  if (exposes.length) {
    const basePath = deriveBasePath(exposes[0].path);
    lines.push(`endpoints:`);
    lines.push(`  basePath: ${basePath}`);
    lines.push(`  versions:`);
    lines.push(`    - version: v1`);
    lines.push(`      operations:`);
    for (const ep of exposes) {
      const relativePath = makeRelativePath(ep.path, basePath);
      lines.push(`        - method: ${ep.method}`);
      lines.push(`          path: ${relativePath}`);
      lines.push(`          useCase: ${ep.useCase}`);
      if (ep.description) lines.push(`          description: "${ep.description}"`);
    }
    lines.push(``);
  }

  // ── listeners ─────────────────────────────────────────────────────────────
  if (consumedEvents.length) {
    lines.push(`# Events consumed from other modules`);
    lines.push(`listeners:`);
    for (const ev of consumedEvents) {
      lines.push(`  - event: ${ev.event}`);
      lines.push(`    producer: ${ev.producer}`);
      lines.push(`    topic: ${ev.topic}`);
      lines.push(`    useCase: ${ev.consumerUseCase}`);
      lines.push(`    fields:`);
      lines.push(`      # TODO: add payload fields — must match ${ev.producer} module's event declaration`);
      lines.push(`      # - name: fieldName`);
      lines.push(`      #   type: String`);
    }
    lines.push(``);
  }

  // ── ports ─────────────────────────────────────────────────────────────────
  if (outboundCalls.length) {
    const seenServices = new Set();

    lines.push(`# HTTP clients called synchronously by this module`);
    lines.push(`ports:`);
    for (const call of outboundCalls) {
      const serviceName      = call.port;
      const isFirstOfService = !seenServices.has(serviceName);
      seenServices.add(serviceName);

      for (const httpEntry of (call.using || [])) {
        const methodName = deriveMethodName(httpEntry, call.calls);
        lines.push(`  - name: ${methodName}`);
        lines.push(`    service: ${serviceName}`);
        lines.push(`    target: ${call.calls}`);
        if (isFirstOfService) {
          lines.push(`    baseUrl: http://localhost:8080  # TODO: set ${call.calls} service URL`);
        }
        lines.push(`    http: ${httpEntry}`);
        lines.push(`    fields:`);
        lines.push(`      # TODO: add response fields`);
        lines.push(`      # - name: fieldName`);
        lines.push(`      #   type: String`);
      }
    }
    lines.push(``);
  }

  return lines.join('\n');
}

// ── Helpers ───────────────────────────────────────────────────────────────────

/**
 * Extract the basePath (first non-param segment) from a full endpoint path.
 * e.g. "/orders/{id}/confirm" → "/orders"
 */
function deriveBasePath(fullPath) {
  const segment = (fullPath || '').replace(/^\//, '').split('/')[0];
  return '/' + segment;
}

/**
 * Return a path relative to basePath for use in endpoints[].operations[].path.
 * e.g. ("/orders/{id}", "/orders") → "/{id}"
 *      ("/orders",      "/orders") → "/"
 */
function makeRelativePath(fullPath, basePath) {
  const normalized = '/' + (fullPath || '').replace(/^\//, '');
  const base       = '/' + (basePath || '').replace(/^\//, '').replace(/\/$/, '');
  if (normalized === base) return '/';
  if (normalized.startsWith(base + '/')) return normalized.slice(base.length);
  return normalized;
}

/**
 * Derive a camelCase Java method name from "VERB /path" (e.g. "GET /customers/{id}").
 * Handles sub-resources: "GET /screenings/{id}/seats" → "findAvailableSeats".
 */
function deriveMethodName(httpEntry, targetModule) {
  const parts  = httpEntry.trim().split(/\s+/);
  const verb   = (parts[0] || 'GET').toUpperCase();
  const urlPath = parts[1] || '/';

  const segments     = urlPath.split('/').filter(s => s.length > 0);
  const hasId        = segments.some(s => s.startsWith('{'));
  const resourceSegs = segments.filter(s => !s.startsWith('{'));
  const lastResource = resourceSegs[resourceSegs.length - 1]
    || toCamelCase(targetModule || 'resource');
  const singular = pluralize.singular(lastResource);
  const pascal   = toPascalCase(singular);

  // Sub-resource with path param: GET /screenings/{id}/seats → findAvailableSeats
  if (verb === 'GET' && hasId && resourceSegs.length > 1) {
    return `find${toPascalCase(lastResource)}`;
  }
  if (verb === 'GET' && hasId)            return `find${pascal}ById`;
  if (verb === 'GET')                      return `findAll${toPascalCase(lastResource)}`;
  if (verb === 'POST')                     return `create${pascal}`;
  if (verb === 'PUT' || verb === 'PATCH') return `update${pascal}`;
  if (verb === 'DELETE')                   return `delete${pascal}`;
  return toCamelCase(`${verb.toLowerCase()}_${lastResource}`);
}

module.exports = generateSystemCommand;
