const defaults = require('../../config/defaults.json');
const {
  toPackagePath,
  getApplicationClassName,
  getFullPackageName,
  toPascalCase,
  toSnakeCase,
  pluralizeWord,
  getBaseEntity
} = require('./naming');

/**
 * Build context for base project generation
 */
function buildBaseContext(answers) {
  const packageName = getFullPackageName(answers.groupId, answers.artifactId);
  const packagePath = toPackagePath(packageName);
  const applicationClassName = getApplicationClassName(answers.artifactId);
  
  const context = {
    projectName: answers.projectName || answers.artifactId,
    artifactId: answers.artifactId,
    groupId: answers.groupId,
    version: defaults.version,
    packageName,
    packagePath,
    applicationClassName,
    javaVersion: answers.javaVersion || defaults.javaVersion,
    springBootVersion: answers.springBootVersion || defaults.springBootVersion,
    dependencyManagementVersion: defaults.dependencyManagementVersion,
    springModulithVersion: defaults.springModulithVersion,
    springCloudVersion: defaults.springCloudVersion,
    gradleVersion: defaults.gradleVersion,
    dependencies: answers.dependencies || [],
    author: answers.author || 'Generated by eva4j',
    createdDate: new Date().toISOString().split('T')[0],
    license: 'MIT',
    description: answers.description || `Spring Boot application: ${answers.artifactId}`,
    ...buildDatabaseContext(answers),
    ...buildServerContext(answers),
    features: {
      ...defaults.features,
      includeAudit: answers.dependencies?.includes('data-jpa'),
      ...answers.features
    },
    testing: defaults.testing,
    loggingLevel: defaults.logging.level
  };
  
  return context;
}

/**
 * Build database configuration context
 */
function buildDatabaseContext(answers) {
  if (!answers.dependencies?.includes('data-jpa')) {
    return {};
  }
  
  const databaseType = answers.databaseType || 'h2';
  const databaseName = answers.artifactId.replace(/-/g, '_');
  
  const dbConfig = {
    h2: {
      driver: 'com.h2.database:h2',
      driverClass: 'org.h2.Driver',
      url: `jdbc:h2:mem:${databaseName}`,
      username: 'sa',
      password: '',
      hibernateDialect: 'org.hibernate.dialect.H2Dialect',
      testcontainer: 'h2'
    },
    postgresql: {
      driver: 'org.postgresql:postgresql',
      driverClass: 'org.postgresql.Driver',
      url: `jdbc:postgresql://localhost:5432/${databaseName}`,
      username: answers.databaseUsername || 'postgres',
      password: answers.databasePassword || 'postgres',
      hibernateDialect: 'org.hibernate.dialect.PostgreSQLDialect',
      testcontainer: 'postgresql'
    },
    mysql: {
      driver: 'com.mysql:mysql-connector-j',
      driverClass: 'com.mysql.cj.jdbc.Driver',
      url: `jdbc:mysql://localhost:3306/${databaseName}`,
      username: answers.databaseUsername || 'root',
      password: answers.databasePassword || 'root',
      hibernateDialect: 'org.hibernate.dialect.MySQLDialect',
      testcontainer: 'mysql'
    }
  };
  
  const config = dbConfig[databaseType];
  
  return {
    databaseType,
    databaseName,
    databaseDriver: config.driver,
    databaseDriverClass: config.driverClass,
    databaseUrl: config.url,
    databaseUsername: config.username,
    databasePassword: config.password,
    hibernateDialect: config.hibernateDialect,
    databaseTestcontainer: config.testcontainer,
    ddlAuto: defaults.database.ddlAuto,
    showSql: defaults.database.showSql
  };
}

/**
 * Build server configuration context
 */
function buildServerContext(answers) {
  return {
    serverPort: answers.serverPort || defaults.server.port,
    contextPath: answers.contextPath || defaults.server.contextPath
  };
}

/**
 * Build context for module generation
 */
function buildModuleContext(baseContext, moduleName, moduleOptions = {}) {
  const className = toPascalCase(moduleName);
  const tableName = toSnakeCase(pluralizeWord(moduleName));
  const moduleNamePlural = pluralizeWord(moduleName);
  
  const hasSoftDelete = moduleOptions.hasSoftDelete ?? defaults.module.hasSoftDelete;
  const hasAudit = moduleOptions.hasAudit ?? defaults.module.hasAudit;
  const baseEntityClass = getBaseEntity(hasSoftDelete, hasAudit);
  
  return {
    ...baseContext,
    moduleName,
    moduleNamePlural,
    className,
    tableName,
    hasSoftDelete,
    hasAudit,
    baseEntityClass,
    generateTests: moduleOptions.generateTests ?? defaults.module.generateTests
  };
}

module.exports = {
  buildBaseContext,
  buildModuleContext
};
